repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff format --config config/ruff.toml --check
        language: system
        types: [python]
      - id: ruff-check
        name: ruff check
        entry: ruff check --config config/ruff.toml
        language: system
        types: [python]
