repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --select=C,E,F,W,B
          - --extend-ignore=E203,E501,W503 # no select B950 for now and added W503 since it is incompatible with PEP8, rest is to be compatible with black, see https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length
        additional_dependencies:
          - flake8-bugbear

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0 # need 5.12.0 to fix RuntimeError: The Poetry configuration is invalid
    hooks:
      - id: isort
        args:
          - --multi-line=3
          - --profile=black # to be compatible with black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: ^config/

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args:
          - src
          - tests
        pass_filenames: false
        additional_dependencies:
          - pydantic>=2.0.0
          - pytest
          - rich
          - typer
          - types-PyYAML

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
        # additional_dependencies: [jupytext]  # optional, only if you're using Jupytext
      - id: nbqa-pyupgrade
        args: [--py310-plus]
      - id: nbqa-isort
        args: [--float-to-top, --profile=black]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.0
    hooks:
      - id: nbstripout

  - repo: local
    hooks:
      - id: pdm-export
        name: pdm-export
        entry: pdm export
        args:
          - -o
          - requirements.txt
          - --without-hashes
          - --pyproject
        language: system
        pass_filenames: false
      - id: pdm-lock-check
        name: pdm-lock-check
        entry: pdm lock --check
        language: system
        pass_filenames: false
      - id: pytest-check
        name: pytest-check
        entry: pdm run pytest
        args:
          - tests
          - -vv
        language: system
        pass_filenames: false
        always_run: true
